/*spring.application.name=app_security*/
/*Documento de configuracióin  de los beans de Spring todo lo que se configura aquí. se va a cargar en el 
 *contenedor de Spring
*/

spring.security.user.name=debugger
spring.security.user.password=ideas
spring.security.user.roles=VIEWER